### ISSUE TITLE
Посчитать площадь неизвестной фигуры - это как?

### ISSUE THREAD

**Issue by AsValeO** [SGPTim/MindboxTask#1]
Ты понял этот вопрос? Ладно если многоугольник, но неизвестной фигуры..
Посмотри другие репо. Интересно люди извращаются..

**Comment by SGPTim** [comment]
Вы имеете ввиду что у абстрактной фигуры есть метод GetArea, который значит что у каждой фигуры можно поробовать посчитать площадь. Я правильно понял?

**Comment by AsValeO** [comment]
Я не работодатель. Я тоже выполнял это задание. Поищи по репозиториям по запросу mindbox, там много интересных и неожиданных решений. Постановка вопроса совершенно неправильная, я вот к чему. Удачи!
